# Generated by Django 5.1.4 on 2026-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.AddField(
            model_name="student",
            name="telegram",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
