# Generated by Django 5.1.4 on 2026-04-05 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_student_email_student_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "course_admin"},
                related_name="admin_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="schedule",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("excused", "Excused"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("course_admin", "Course admin"),
                    ("teacher", "Teacher"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
