# Generated by Django 5.1.4 on 2026-04-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_course_admins_course_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
