# Generated by Django 5.1.4 on 2026-04-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_company_name_user_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
