# Generated by Django 5.1.4 on 2026-04-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auditorium_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("course_admin", "Company admin"),
                    ("teacher", "Teacher"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
