# Generated by Codex on 2026-04-05

from django.db import migrations


def fill_group_company_name(apps, schema_editor):
    Group = apps.get_model("core", "Group")
    User = apps.get_model("core", "User")

    for group in Group.objects.filter(company_name=""):
        company_name = ""
        if group.course_id:
            admins = (
                User.objects.filter(admin_courses__id=group.course_id)
                .order_by("date_joined")
            )
            admin = admins.first()
            if admin and admin.company_name:
                company_name = admin.company_name
        if not company_name and group.teacher_id:
            teacher = User.objects.filter(id=group.teacher_id).first()
            if teacher and teacher.company_name:
                company_name = teacher.company_name
        if not company_name:
            students = group.students.all().order_by("created_at")
            student = students.first()
            if student and student.company_name:
                company_name = student.company_name
        if company_name:
            group.company_name = company_name
            group.save(update_fields=["company_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_group_company_name_alter_group_course_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_group_company_name, migrations.RunPython.noop),
    ]

