# Generated by Django 5.1.4 on 2026-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_fill_group_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
