# Generated by Django 5.1.4 on 2026-04-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_user_address_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("course_admin", "Company admin"),
                    ("manager", "Manager"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
