# Generated by Django 5.1.4 on 2026-04-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_student_user_alter_user_role"),
        ("core", "0016_user_max_managers"),
    ]

    operations = []
