# Generated by Django 5.1.4 on 2026-04-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20260407_1908"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("course_interest", models.CharField(blank=True, max_length=200)),
                ("trial_attended", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("trial_scheduled", "Trial scheduled"),
                            ("attended", "Attended"),
                            ("not_attended", "Not attended"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("trial_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField(blank=True)),
                ("converted_to_student", models.BooleanField(default=False)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("not_paid", "Not paid"),
                            ("partial", "Partial"),
                        ],
                        default="not_paid",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_leads",
                        to="core.group",
                    ),
                ),
            ],
        ),
    ]
