# Generated by Django 5.1.4 on 2026-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
