# Generated by Django 5.1.4 on 2026-04-26 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_homework_task_management_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_blocks",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Maximum number of sections allowed on a single landing page",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="max_pages",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maximum number of landing pages this course admin can create",
            ),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("moderation_comment", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_landing_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "course_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landing_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LandingHeaderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_header_links",
                        to="core.landingpage",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="LandingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("about", "About Us"),
                            ("course_grid", "Course Grid"),
                            ("teacher_slider", "Teacher Slider"),
                            ("statistics", "Statistics"),
                            ("lead_form", "Lead Form"),
                            ("testimonials", "Testimonials"),
                            ("faq", "FAQ"),
                            ("pricing", "Pricing Table"),
                            ("video", "Video Block"),
                            ("gallery", "Gallery"),
                            ("contacts", "Contacts & Map"),
                            ("cta", "Call To Action"),
                            ("partners", "Partners"),
                            ("benefits", "Benefits"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.landingpage",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
