# Generated by Django 5.2.13 on 2026-05-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_user_max_blocks_user_max_pages_landingpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "course_interest",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Course of Interest"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper-intermediate", "Upper-Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=50,
                        verbose_name="Experience Level",
                    ),
                ),
                (
                    "learning_goal",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Learning Goal"
                    ),
                ),
                (
                    "budget",
                    models.CharField(blank=True, max_length=100, verbose_name="Budget"),
                ),
                (
                    "schedule_preference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Schedule Preference"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="How Did You Find Us?"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "In Processing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Application",
                "verbose_name_plural": "Student Applications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TeacherApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Specialization"
                    ),
                ),
                (
                    "expected_salary",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Expected Salary"
                    ),
                ),
                ("education", models.TextField(blank=True, verbose_name="Education")),
                ("about", models.TextField(blank=True, verbose_name="About Me")),
                (
                    "availability",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary with keys like 'mon-morning', 'tue-afternoon', etc.",
                        verbose_name="Available Time Slots",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("both", "Both"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Teaching Format",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "In Processing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teacher Application",
                "verbose_name_plural": "Teacher Applications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-is_promoted", "-created_at"]},
        ),
        migrations.AddField(
            model_name="course",
            name="is_promoted",
            field=models.BooleanField(
                default=False, help_text="Продвигается ли курс (TOP)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="promoted_until",
            field=models.DateTimeField(
                blank=True, help_text="До какой даты продвигается", null=True
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Company Name")),
                (
                    "slug",
                    models.SlugField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="companies/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("languages", "Languages"),
                            ("it", "IT & Technology"),
                            ("crafts", "Crafts & Handmade"),
                            ("sports", "Sports & Fitness"),
                            ("music", "Music & Arts"),
                            ("business", "Business & Finance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Бишкек", "Бишкек"),
                            ("Ош", "Ош"),
                            ("Талас", "Талас"),
                            ("Нарын", "Нарын"),
                            ("Джалал-Абад", "Джалал-Абад"),
                            ("Каракол", "Каракол"),
                            ("Онлайн", "Онлайн"),
                        ],
                        max_length=20,
                        verbose_name="City",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WhatsApp"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reviews Count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "course_admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JobVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Position Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("languages", "Languages"),
                            ("it", "IT & Technology"),
                            ("crafts", "Crafts & Handmade"),
                            ("sports", "Sports & Fitness"),
                            ("music", "Music & Arts"),
                            ("business", "Business & Finance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Бишкек", "Бишкек"),
                            ("Ош", "Ош"),
                            ("Талас", "Талас"),
                            ("Нарын", "Нарын"),
                            ("Джалал-Абад", "Джалал-Абад"),
                            ("Каракол", "Каракол"),
                            ("Онлайн", "Онлайн"),
                        ],
                        max_length=20,
                        verbose_name="City",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Min Salary"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Max Salary"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Work Schedule"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requirements"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Responsibilities"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_promoted",
                    models.BooleanField(
                        default=False, help_text="Продвигается ли вакансия (TOP)"
                    ),
                ),
                (
                    "promoted_until",
                    models.DateTimeField(
                        blank=True, help_text="До какой даты продвигается", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Vacancy",
                "verbose_name_plural": "Job Vacancies",
                "ordering": ["-is_promoted", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код промокода (например: START2026, OSH500)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("coins", "eduCoins (монеты)"),
                            ("bonus_limit", "Бонусный лимит курсов"),
                        ],
                        default="coins",
                        max_length=20,
                    ),
                ),
                (
                    "reward_value",
                    models.PositiveIntegerField(
                        help_text="Количество монет или дополнительный лимит"
                    ),
                ),
                (
                    "max_usages",
                    models.PositiveIntegerField(
                        default=100, help_text="Максимальное количество активаций"
                    ),
                ),
                ("current_usages", models.PositiveIntegerField(default=0)),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, help_text="Дата истечения действия", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promo_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo Code",
                "verbose_name_plural": "Promo Codes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PublicCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Course Title"),
                ),
                ("slug", models.SlugField(max_length=150, verbose_name="Slug")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(verbose_name="Duration (weeks)"),
                ),
                (
                    "lesson_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lesson Duration (minutes)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("languages", "Languages"),
                            ("it", "IT & Technology"),
                            ("crafts", "Crafts & Handmade"),
                            ("sports", "Sports & Fitness"),
                            ("music", "Music & Arts"),
                            ("business", "Business & Finance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Бишкек", "Бишкек"),
                            ("Ош", "Ош"),
                            ("Талас", "Талас"),
                            ("Нарын", "Нарын"),
                            ("Джалал-Абад", "Джалал-Абад"),
                            ("Каракол", "Каракол"),
                            ("Онлайн", "Онлайн"),
                        ],
                        max_length=20,
                        verbose_name="City",
                    ),
                ),
                ("schedule", models.TextField(blank=True, verbose_name="Schedule")),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Requirements"),
                ),
                (
                    "curriculum",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of lessons/modules",
                        verbose_name="Curriculum",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
                    ),
                ),
                (
                    "reviews_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reviews Count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Course",
                "verbose_name_plural": "Public Courses",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CourseApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Experience Level"
                    ),
                ),
                (
                    "learning_goal",
                    models.TextField(blank=True, verbose_name="Learning Goal"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "In Processing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.publiccourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Application",
                "verbose_name_plural": "Course Applications",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Положительное для пополнения, отрицательное для списания"
                    ),
                ),
                (
                    "reason",
                    models.CharField(help_text="Причина транзакции", max_length=500),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Списание"),
                            ("bonus", "Бонус"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=1000, help_text="Баланс eduCoin"
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["course_admin", "manager"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Balance",
                "verbose_name_plural": "User Balances",
            },
        ),
    ]
