# Generated by Django 5.2.13 on 2026-05-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_studentapplication_teacherapplication_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Название компании", max_length=200, unique=True
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(default=0, help_text="Баланс eduCoins"),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Balance",
                "verbose_name_plural": "Company Balances",
            },
        ),
        migrations.RemoveField(
            model_name="userbalance",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="company_name",
            field=models.CharField(
                default=1, help_text="Название компании", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, инициировавший транзакцию (необязательно)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["company_name", "-timestamp"],
                name="core_transa_company_fb5998_idx",
            ),
        ),
        migrations.DeleteModel(
            name="UserBalance",
        ),
    ]
