# Generated by Django 5.2.13 on 2026-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_companybalance_remove_userbalance_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvacancy",
            name="applications",
            field=models.PositiveIntegerField(default=0, verbose_name="Applications"),
        ),
        migrations.AddField(
            model_name="jobvacancy",
            name="is_urgent",
            field=models.BooleanField(default=False, help_text="Срочный бейдж"),
        ),
        migrations.AddField(
            model_name="jobvacancy",
            name="urgent_until",
            field=models.DateTimeField(
                blank=True, help_text="До какой даты бейдж", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobvacancy",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="applications_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Applications Count"
            ),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Course Image",
            ),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="is_promoted",
            field=models.BooleanField(
                default=False, help_text="Продвигается ли курс (TOP)"
            ),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="is_urgent",
            field=models.BooleanField(default=False, help_text="Срочный бейдж"),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="promoted_until",
            field=models.DateTimeField(
                blank=True, help_text="До какой даты продвигается", null=True
            ),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="urgent_until",
            field=models.DateTimeField(
                blank=True, help_text="До какой даты бейдж", null=True
            ),
        ),
        migrations.AddField(
            model_name="publiccourse",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
    ]
