# Generated by Django 5.2.13 on 2026-05-12 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_auditorium_company_companybalance_company_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority", "due_date"]},
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("course_admin", "Company admin"),
                    ("manager", "Manager"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TaskLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("task_lead", "Task Lead"),
                            ("team_lead", "Team Lead"),
                            ("project_manager", "Project Manager"),
                        ],
                        default="task_lead",
                        max_length=30,
                        verbose_name="Роль в команде",
                    ),
                ),
                (
                    "team_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество подчинённых менеджеров",
                        verbose_name="Размер команды",
                    ),
                ),
                (
                    "max_tasks",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Максимальное количество активных задач",
                        verbose_name="Максимальное количество задач",
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="От 0 до 100",
                        max_digits=5,
                        verbose_name="Оценка эффективности",
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Описание основных обязанностей",
                        verbose_name="Обязанности",
                    ),
                ),
                (
                    "target_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ключевые показатели эффективности (KPI)",
                        verbose_name="Целевые показатели",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата начала работы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_leads",
                        to="core.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_lead_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Lead",
                "verbose_name_plural": "Task Leads",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="task_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Task Lead, ответственный за задачу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.tasklead",
            ),
        ),
    ]
