# Generated by Django 4.2.13 on 2026-06-01 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_task_options_task_completed_at_task_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(default=0, help_text="Баланс eduCoins"),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Balance",
                "verbose_name_plural": "User Balances",
            },
        ),
        migrations.CreateModel(
            name="UserTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Положительное для пополнения, отрицательное для списания"
                    ),
                ),
                (
                    "reason",
                    models.CharField(help_text="Причина транзакции", max_length=500),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Списание"),
                            ("bonus", "Бонус"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Transaction",
                "verbose_name_plural": "User Transactions",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_usertr_user_id_0cd4a9_idx",
                    )
                ],
            },
        ),
    ]
