# Generated by Django 4.2.13 on 2026-06-01 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_userbalance_usertransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0, help_text="Остаток монет промокода"
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "promo_code",
                    models.OneToOneField(
                        help_text="Промокод",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="core.promocode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo Balance",
                "verbose_name_plural": "Promo Balances",
            },
        ),
        migrations.CreateModel(
            name="PromoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Положительное для пополнения, отрицательное для списания"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Списание (выплата)"),
                        ],
                        default="deposit",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "promo_code",
                    models.ForeignKey(
                        help_text="Промокод",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, получивший выплату (при WITHDRAWAL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo Transaction",
                "verbose_name_plural": "Promo Transactions",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["promo_code", "-timestamp"],
                        name="core_promot_promo_c_0d004a_idx",
                    )
                ],
            },
        ),
    ]
