# Generated by Django 4.2.13 on 2026-06-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_promobalance_promotransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.company",
            ),
        ),
    ]
