# Generated by Django 4.2.13 on 2026-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_payment_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="facebook",
            field=models.CharField(blank=True, max_length=100, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="company",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Instagram"
            ),
        ),
    ]
