# Generated by Django 5.2.13 on 2026-06-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_company_facebook_company_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram chat ID для уведомлений', null=True),
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.IntegerField(blank=True, help_text='ID сообщения в Telegram', null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Chat ID группы/канала где было отправлено', null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core.triallead')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Assignment',
                'verbose_name_plural': 'Lead Assignments',
            },
        ),
    ]
