# Generated by Django 5.2.13 on 2026-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_telegram_chat_id_leadassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активна'), ('rejected', 'Отклонена')], default='active', help_text='Статус группы: active — активна, pending — ожидает подтверждения учителем', max_length=20),
        ),
    ]
