# Generated by Django 5.2.13 on 2026-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_telegrambindcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rejection_comment',
            field=models.TextField(blank=True, help_text='Комментарий учителя при отказе'),
        ),
        migrations.AddField(
            model_name='group',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество отказов учителя'),
        ),
    ]
