# Generated by Django 5.2.13 on 2026-06-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_group_rejection_comment_group_rejection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='training_months',
            field=models.PositiveIntegerField(default=1, help_text='Количество месяцев обучения (1–6)'),
        ),
        migrations.CreateModel(
            name='GroupMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(help_text='Номер месяца (1, 2, 3...)')),
                ('teacher_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Зарплата преподавателя за этот месяц (заполняется курс-админом)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершён')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Когда месяц был отмечен как завершённый', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='core.group')),
            ],
            options={
                'verbose_name': 'Month of group',
                'verbose_name_plural': 'Months of group',
                'ordering': ('group', 'month_number'),
                'unique_together': {('group', 'month_number')},
            },
        ),
    ]
