# Generated by Django 5.2.13 on 2026-06-16 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_group_training_months_groupmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='training_months',
            field=models.PositiveIntegerField(default=1, help_text='Количество месяцев обучения (1–6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
