# Generated by Django 5.2.13 on 2026-06-16 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_group_training_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Описание расхода', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма расхода', max_digits=10)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('materials', 'Учебные материалы'), ('marketing', 'Маркетинг'), ('equipment', 'Оборудование'), ('tax', 'Налоги'), ('other', 'Прочее')], default='other', help_text='Категория расхода', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.company')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
