# Generated by Django 5.2.13 on 2026-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Индивидуальная цена для группы (если не указана, используется цена курса)', max_digits=10, null=True),
        ),
    ]
