# Generated by Django 5.2.13 on 2026-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_group_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmonth',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Индивидуальная цена для этого месяца (если не указана, используется цена группы или курса)', max_digits=10, null=True),
        ),
    ]
