# Generated by Django 5.2.13 on 2026-06-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_groupmonth_custom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='custom_price',
        ),
        migrations.RemoveField(
            model_name='group',
            name='training_months',
        ),
        migrations.RemoveField(
            model_name='groupmonth',
            name='custom_price',
        ),
    ]
