# Generated by Django 5.2.13 on 2026-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_group_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lessons_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Количество уроков в месяц', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_months',
            field=models.PositiveIntegerField(blank=True, help_text='Сколько месяцев длится группа', null=True),
        ),
    ]
