# Generated by Django 5.2.13 on 2026-06-17 11:46

from django.db import migrations


def backfill_company_fk(apps, schema_editor):
    """Заполняет company_id из company_name для всех моделей, у которых есть оба поля."""
    Company = apps.get_model("core", "Company")
    
    # Строим словарь: company_name -> company_id
    company_map = {}
    for c in Company.objects.all():
        key = c.name.strip().lower()
        if key:
            company_map[key] = c
    
    models_to_backfill = [
        "User", "Auditorium", "Student", "Group", "TrialLead",
        "Task", "LandingPage", "LandingHeaderLink", "HomeworkTask",
        "TeacherApplication", "StudentApplication", "CompanyBalance", "Transaction",
    ]
    
    total_updated = 0
    for model_name in models_to_backfill:
        Model = apps.get_model("core", model_name)
        if Model is None:
            continue
        
        # Находим записи, у которых company=NULL, но company_name задан
        qs = Model.objects.filter(company__isnull=True).exclude(company_name="")
        updated = 0
        for obj in qs:
            key = obj.company_name.strip().lower()
            if key in company_map:
                obj.company = company_map[key]
                obj.save(update_fields=["company"])
                updated += 1
        
        if updated:
            print(f"  {model_name}: обновлено {updated} записей")
            total_updated += updated
    
    print(f"Всего обновлено: {total_updated} записей")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_group_lessons_per_month_group_total_months"),
    ]

    operations = [
        migrations.RunPython(backfill_company_fk, reverse_code=migrations.RunPython.noop),
    ]
