# Generated by Django 5.2.13 on 2026-06-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_backfill_company_fk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_company_fb5998_idx',
        ),
        migrations.RemoveField(
            model_name='auditorium',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companybalance',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='homeworktask',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='landingheaderlink',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='triallead',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
