# Generated by Django 5.2.13 on 2026-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_transaction_core_transa_company_fb5998_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент от оплаты, который получает учитель (0-100)', max_digits=5),
        ),
    ]
