# Generated by Django 5.2.13 on 2026-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_group_teacher_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Дата, до которой нужно оплатить (для напоминаний)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда было отправлено последнее напоминание об оплате', null=True),
        ),
    ]
