# Generated by Django 5.2.13 on 2026-06-20 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_payment_due_date_and_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен студенту'), ('signed', 'Подписан'), ('cancelled', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('terms', models.TextField(blank=True, help_text='Особые условия, не указанные в шаблоне', verbose_name='Дополнительные условия')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.company', verbose_name='Компания (учебный центр)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.group', verbose_name='Группа / курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('-created_at',),
            },
        ),
    ]
