# Generated by Django 5.2.13 on 2026-06-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_contract_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартный шаблон', max_length=200, verbose_name='Название шаблона')),
                ('html_content', models.TextField(blank=True, help_text='HTML шаблон с переменными Django: {{ student_name }}, {{ course_name }}, {{ amount }}, {{ start_date }}, {{ company_name }}, {{ admin_name }}, {{ group_name }}, {{ student_phone }}', verbose_name='HTML содержимое')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать этот шаблон для всех новых договоров компании', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ('-is_default', '-created_at'),
            },
        ),
    ]
