# Generated by Django 5.2.13 on 2026-10-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_homework_multiple_library_resources'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='core_librar_company_51bde1_idx',
            old_name='core_librar_company_7756aa_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='core_librar_company_d31914_idx',
            old_name='core_librar_company_3d9b0e_idx',
        ),
        migrations.RenameIndex(
            model_name='libraryitem',
            new_name='core_librar_company_021727_idx',
            old_name='core_librar_company_c12d4a_idx',
        ),
    ]
