# Generated by Django 5.2.13 on 2026-06-17 07:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_remove_group_custom_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('income_statement', 'Отчёт о прибылях и убытках'), ('balance_sheet', 'Баланс'), ('cash_flow', 'Движение денежных средств'), ('debt_report', 'Отчёт по задолженностям'), ('salary_report', 'Отчёт по зарплатам'), ('custom', 'Пользовательский')], max_length=30, verbose_name='Тип отчёта')),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
                ('pdf_file', models.FileField(blank=True, help_text='Скачать PDF отчёт', null=True, upload_to='reports/%Y/%m/', verbose_name='PDF файл')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_reports', to='core.company', verbose_name='Компания')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Сгенерирован пользователем')),
            ],
            options={
                'verbose_name': 'Бухгалтерский отчёт',
                'verbose_name_plural': 'Бухгалтерские отчёты',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('rent', 'Аренда'), ('utilities', 'Коммунальные услуги'), ('materials', 'Учебные материалы'), ('marketing', 'Маркетинг'), ('equipment', 'Оборудование'), ('tax', 'Налоги'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Максимальная сумма расходов по этой категории', max_digits=12, verbose_name='Лимит бюджета')),
                ('period_start', models.DateField(help_text='Дата начала бюджетного периода', verbose_name='Начало периода')),
                ('period_end', models.DateField(help_text='Дата окончания бюджетного периода', verbose_name='Конец периода')),
                ('is_active', models.BooleanField(default=True, help_text='Если снят — бюджет не учитывается', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(help_text='Процент от бюджета, при котором сработает алерт', verbose_name='Порог (%)')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finance.budget', verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Оповещение бюджета',
                'verbose_name_plural': 'Оповещения бюджетов',
            },
        ),
        migrations.CreateModel(
            name='PeriodComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_1_label', models.CharField(help_text="Например: 'Январь 2026' или 'Q1 2026'", max_length=50, verbose_name='Период 1 (базовый)')),
                ('period_2_label', models.CharField(help_text="Например: 'Февраль 2026' или 'Q1 2025'", max_length=50, verbose_name='Период 2 (сравнение)')),
                ('period_1_start', models.DateField(verbose_name='Начало периода 1')),
                ('period_1_end', models.DateField(verbose_name='Конец периода 1')),
                ('period_2_start', models.DateField(verbose_name='Начало периода 2')),
                ('period_2_end', models.DateField(verbose_name='Конец периода 2')),
                ('comparison_date', models.DateField(auto_now_add=True, verbose_name='Дата сравнения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_comparisons', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сравнение периодов',
                'verbose_name_plural': 'Сравнения периодов',
                'ordering': ['-comparison_date'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('salary', 'Зарплата'), ('profit', 'Прибыль')], max_length=20, verbose_name='Тип прогноза')),
                ('period_month', models.PositiveIntegerField(help_text='Номер месяца (1-12)', verbose_name='Месяц прогноза')),
                ('period_year', models.PositiveIntegerField(verbose_name='Год прогноза')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прогнозируемая сумма')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Заполняется после завершения периода', max_digits=12, null=True, verbose_name='Фактическая сумма')),
                ('confidence_level', models.PositiveIntegerField(default=50, help_text='Уровень уверенности в прогнозе (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
                'ordering': ['-period_year', '-period_month', '-forecast_type'],
                'unique_together': {('company', 'forecast_type', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Месяц (1-12)')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий доход')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общие расходы')),
                ('total_salaries', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарплаты')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Чистая прибыль')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Кол-во студентов')),
                ('total_groups', models.PositiveIntegerField(default=0, verbose_name='Кол-во групп')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Ежемесячная сводка',
                'verbose_name_plural': 'Ежемесячные сводки',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
